- menu_name: "Contatti"

- name: "Mail"
  url: "mailto:giorgio.gambosi@uniroma2.it?&subject=Corso%20Machine%20learning"
  title: "Mail"

- name: "Twitter"
  url: "https://twitter.com/tvmlclass"
  title: "Segui tweet"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"